config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  namespace :admin do
    root 'admin/events#index'
    resources :events do
      resources :state, only: [:create]
    end
  end

  devise_for :users

  root 'events#index'
  resources :events
end

app/models/admin.rb
# frozen_string_literal: true

# Admin model
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

# Model class for manages the data, logic and rules of events
class Event < ApplicationRecord
  include AASM

  aasm(:state) do
    state :pending, initial: true
    state :approved
    state :rejected

    event :approve do
      transitions from: %i[pending rejected], to: :approved
    end

    event :reject do
      transitions from: %i[pending approved], to: :rejected
    end

    event :to_pending do
      transitions from: %i[rejected approved], to: :pending
    end
  end

  belongs_to :user

  PAGES_COUNT = 5
  URL_FORMAT = \
    /(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?/ix.freeze
  validates :title, presence: true, length: { in: 1..30 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :location, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate  :end_time_after_start_time
  validates :organizer_telegram, presence: true
  validates :organizer_email, presence: true
  validates :organizer_email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :link, presence: true
  validates :link, format: { with: URL_FORMAT }

  scope :order_by_pub_date, -> { approved.order('updated_at DESC') }

  paginates_per PAGES_COUNT

  private

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    errors.add(:end_time, I18n.t('common.date_notice')) if end_time < start_time
  end
end

app/models/user.rb
# frozen_string_literal: true

# User model description
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

class Admin
  # Base controller for admin namespace
  class BaseController < ApplicationController
    layout 'admin'

    before_action :authenticate_admin!
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

class Admin
  # Controller class for events actions
  class EventsController < Admin::BaseController
    before_action :set_event, only: %i[show update edit destroy]

    def index
      @events = EventsQuery.new(Event.all, params).call.page(params[:page])
    end

    def show; end

    def edit; end

    def update
      if @event.update(event_params)
        redirect_to admin_event_path(@event), notice: t('.success')
      else
        render :edit, notice: t('.fail')
      end
    end

    def destroy
      @event.destroy
      redirect_to admin_events_path, notice: t('.success')
    end

    private

    def set_event
      @event = Event.find(params[:id]).decorate
    end

    def event_params
      params.require(:event).permit(
        :title,
        :description,
        :location,
        :start_time,
        :end_time,
        :organizer_email,
        :organizer_telegram,
        :link
      )
    end
  end
end

app/controllers/admin/state_controller.rb
# frozen_string_literal: true

class Admin
  # For switching event state
  class StateController < Admin::BaseController
    before_action :set_event, only: [:create]

    def create
      if state_event_valid?
        @event.send params[:event]

        redirect_to admin_events_path, notice: t('.success', { state: @event.state }) if @event.save
      else
        redirect_to admin_event_path(@event), notice: t('.fail')
      end
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    def state_event_valid?
      @event.aasm(:state).events(permitted: true).map(&:name).include?(params[:event].to_sym)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Main app controller
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_current_user)
    current_admin ? admin_events_path : root_path
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Controller class for events actions
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_event, only: %i[update edit destroy]

  def index
    @events = Event.order_by_pub_date.page(params[:page])
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: t('.success')
    else
      render :edit, notice: t('.fail')
    end
  end

  def create
    @event = CreateEvent.call(event_params, current_user, request.base_url)
    if @event.present?
      redirect_to event_path(@event), notice: t('.success')
    else
      render :new, notice: t('.fail')
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path, notice: t('.success')
  end

  private

  def set_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event).permit(
      :title,
      :description,
      :location,
      :start_time,
      :end_time,
      :organizer_email,
      :organizer_telegram,
      :link
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def human_date(date)
    date&.to_formatted_s(:event_date_format)
  end

  def filter_state(state)
    link_to(state, admin_events_path(state: state))
  end
end

app/views/admin/events/_form.html.slim
= simple_form_for [:admin, @event] do |f|
  .row
    .col-1
    .col
      = f.input :title
      = f.input :description
      = f.input :location
      = f.input :start_time, value: human_date(@event.start_time)
      = f.input :end_time, value: human_date(@event.end_time)
      = f.input :organizer_email
      = f.input :organizer_telegram
      = f.input :link
      = f.submit t('common.submit')
    .col-8
      .row
        .col
          = render 'common/errors', model: @event

app/views/admin/events/edit.html.slim
.conteiner
  .row
    .col-1
    .col
      h1= t('.header')
  = render 'form'

app/views/admin/events/index.html.slim
.conteiner
  .row
    .col-1
    .col
      h1= t('.header')
  .row
        .col-1
        .col-1
          = filter_state(:pending)
        .col-1
          = filter_state(:approved)
        .col-1
          = filter_state(:rejected)
        .col-1
          = filter_state(:all)
  .row
    .col-1
    .col-3
      - @events.each do |event|
          .row
            .col
              .alert.alert-dark
                = link_to event.title, admin_event_path(event), class: 'alert-link'
                .row
                  .col-1
                    = link_to t('common.edit'), edit_admin_event_path(event)
                  .col-1
                    = link_to t('common.destroy'), admin_event_path(event), method: :delete, data: { confirm: t('common.confirm') }
  .row
    .col-1
    .col
      = paginate @events, theme: 'twitter-bootstrap-4'

app/views/admin/events/show.html.slim
 .conteiner
  .row
    .col-1
    .col
      = show_for @event do |e|
        h2= e.attributes :title
        p= e.attributes :description
        p= e.attributes :start_time
        p= e.attributes :end_time
        p= e.attributes :location
        p= e.attributes :organizer_email
        p= e.attributes :organizer_telegram
        p= e.attributes :link
        .row
          - @event.switch_status_bar.each do |button|
            = button
  .row
    .col-1
    .col
      = link_to t('common.home'), admin_events_path

app/views/common/_errors.html.slim
- if model.errors.any?
  - model.errors.full_messages.each do |message|
    .row
      .col-3
        = message

app/views/events/_form.html.slim
= simple_form_for @event do |f|
  .row
    .col-1
    .col
      = f.input :title
      = f.input :description
      = f.input :location
      = f.input :start_time, value: human_date(@event.start_time)
      = f.input :end_time, value: human_date(@event.end_time)
      = f.input :organizer_email
      = f.input :organizer_telegram
      = f.input :link
      = f.submit t('common.submit')
    .col-8
      .row
        .col
          = render 'common/errors', model: @event

app/views/events/index.html.slim
.conteiner
  .row
    .col-1
    .col
      h1= t('.header')
  .row
    .col-1
    .col-3
      - @events.each do |event|
          .row
            .col
              .alert.alert-dark
                = link_to event.title, event_path(event), class: 'alert-link'
                .row
                  .col-1
                    = link_to t('common.edit'), edit_event_path(event)
                  .col-1
                    = link_to t('common.destroy'), event_path(event), method: :delete, data: { confirm: t('common.confirm') }

    .col-3
      .alert.alert-dark
        = link_to t('common.new'), new_event_path, class: 'alert-link'
  .row
    .col-1
    .col
      = paginate @events, theme: 'twitter-bootstrap-4'

app/views/events/show.html.slim
 .conteiner
  .row
    .col-1
    .col
      = show_for @event do |e|
        h2= e.attributes :title
        p= e.attributes :description
        p= e.attributes :start_time
        p= e.attributes :end_time
        p= e.attributes :location
        p= e.attributes :organizer_email
        p= e.attributes :organizer_telegram
        p= e.attributes :link
  .row
    .col-1
    .col
      = link_to t('common.home'), root_path

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title LocalEvents
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .conteiner
      .row
        .col-1
        .col
          - if admin_signed_in?
              a.nav-link href=destroy_admin_session_path data-method="delete" #{t('common.sign_out')}
          - else
              a.nav-link href=new_admin_session_path #{t('common.sign_in')}
              a.nav-link href=new_admin_registration_path #{t('common.registration')}
      .row
        .col-1
        .col
          p.notice= notice
          p.alert= alert
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title LocalEvents
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .conteiner
      .row
        .col-1
        .col
          - if user_signed_in?
              a.nav-link href=destroy_user_session_path data-method="delete" #{t('common.sign_out')}
          - else
              a.nav-link href=new_user_session_path #{t('common.sign_in')}
              a.nav-link href=new_user_registration_path #{t('common.registration')}
      .row
        .col-1
        .col
          p.notice= notice
          p.alert= alert
    = yield

app/views/layouts/event_notify.html.slim
  = link_to 'event', Rails.application.routes.url_helpers.admin_event_url(event, :host => url)